import type { Data } from "./type";

export const state: Data = {
    products: [
        {
            id: 1,
            name: 'Aviator Classic',
            img: '../image/img0.png',
            brand: 'Ray-Ban',
            price: 145,
            size: '25mm',
            color: 'brown',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 2,
            name: 'Wayfarer',
            img: '../image/img1.png',
            brand: 'Ray-Ban',
            price: 140,
            size: '22mm',
            color: 'black',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 3,
            name: 'Clubmaster',
            img: '../image/img2.png',
            brand: 'Ray-Ban',
            price: 135,
            size: '28mm',
            color: 'blue',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 4,
            name: 'Holbrook',
            img: '../image/img3.png',
            brand: 'Oakley',
            price: 150,
            size: '26mm',
            color: 'orange',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 5,
            name: 'Frogskins',
            img: '../image/img4.png',
            brand: 'Oakley',
            price: 140,
            size: '24mm',
            color: 'green',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 6,
            name: 'Hexagonal Flat Lenses',
            img: '../image/img5.png',
            brand: 'Ray-Ban',
            price: 145,
            size: '27mm',
            color: 'brown',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 7,
            name: 'Latch',
            img: '../image/img6.png',
            brand: 'Oakley',
            price: 135,
            size: '23mm',
            color: 'black',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 8,
            name: 'Round Metal',
            img: '../image/img7.png',
            brand: 'Ray-Ban',
            price: 145,
            size: '21mm',
            color: 'blue',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 9,
            name: 'Sutro',
            img: '../image/img8.png',
            brand: 'Oakley',
            price: 150,
            size: '29mm',
            color: 'orange',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
        {
            id: 10,
            name: 'Erika',
            img: '../image/img9.png',
            brand: 'Ray-Ban',
            price: 135,
            size: '20mm',
            color: 'green',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat placeat similique dicta nulla praesentium deserunt. Corporis repellendus deleniti dolores eligendi.',
            count: 1,
        },
    ],
    cart: []
}
